### NumPy vs. Python Lists – Performance Test
##### Let's compare Python lists with NumPy arrays using a simple example.

In [4]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)

#Key Takeaway: NumPy is significantly faster because it performs operations in C, avoiding Python loops.

Python list addition time: 0.09579324722290039
NumPy array addition time: 0.012800931930541992


In [1]:
# Harry Bhai Task
import numpy as np
import time

size  = 10_000

# Python list
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
list_squares = [x ** 2 for x in l1]
end = time.time()

print(end - start)

# NumPy array
arr1 = np.array(list(range(size)))
arr2 = np.array(list(range(size)))

start = time.time()
numpy_squares = arr1 ** 2
end = time.time()

print(end - start)


0.002020120620727539
0.0


### Creating NumPy Arrays
##### NumPy stores data in a contiguous memory block, making access faster than lists.🔹 shape shows the dimensions of an array.

In [7]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


### Memory Efficiency – NumPy vs. Lists
Let's check memory consumption.

In [11]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


### Vectorization – No More Loops!
##### NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level optimization provided by modern processors.

In [24]:
# Python list (loop-based)
list_squares = [x ** 2 for x in list1]

# NumPy (vectorized)
numpy_squares = arr1 ** 2